### ISSUE TITLE
Documentation to automatically registering interface at OS level for private network

### ISSUE THREAD

**Issue by sebastiankr** [hetznercloud/terraform-provider-hcloud#161]
Hi,
I can successfully associate servers with networks. 
```
resource "hcloud_network" "ens10" {
  name = "ens10"
  ip_range = "10.0.0.0/16"
}
resource "hcloud_network_subnet" "ens10" {
  type = "server"
  network_zone = "eu-central"
  ip_range = "10.0.0.0/24"
  network_id = hcloud_network.ens10.id
}

resource "hcloud_server" "node-0" {
  name        = "node-0"
  server_type = "cpx11"
  datacenter  = "nbg1-dc3"
  image       = "ubuntu-18.04"
  ssh_keys    = var.hcloud_ssh_keys
  user_data = templatefile("${path.module}/../../templates/cloud-config.yml.tpl", {
    docker_gpg : file("${path.module}/../../files/docker_gpg"),
    daemon_json : file("${path.module}/../../files/daemon.json")
  })
}

resource "hcloud_server_network" "ens10" {
  server_id  = hcloud_server.node-0.id
  network_id = var.network_id
  ip         = "10.0.0.2"
}
```
In the hetzner console I can see that the network "ens10" is properly attached to the server. But on the server I can only see loopback and eth0:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP mode DEFAULT group default qlen 1000
    link/ether 96:00:00:4f:ea:d4 brd ff:ff:ff:ff:ff:ff
```

How can I automatically register the network interface "ens10"? How would I do it with cloud-init? Should this not be done by the provider with some sort of an `iface` argument?

**Comment by danielgrant** [comment]
I ran into this same issue last week - I'm using an existing `hcloud_network` that already has a number of servers attached to it.

However, I've gone to add a new server via Terraform, and set it up as above (with a new `hcloud_server_network`), and after the server starts there's no sign of the new private network interface. All the tinkering I could do couldn't bring it up.

In the end, I navigated to the Hetzner Cloud Console, and using the web UI I detached the server from the private network, and then re-added it, and the private network interface appeared!

So I suspect there's a step required to finish attaching the private network interface to a newly created server that the current API calls that Terraform is making is not doing, but the Cloud Console web UI is.

@sebastiankr the private network interface should automatically appear on the server once it's been attached to the network correct. Try and detach / reattach the private network via the Hetzner Cloud Console web UI. I know this defeats the purpose of using Terraform, but it's better than nothing until this is fixed...

Edit: should probably add the versions I'm using:

```
Terraform v0.12.24
+ provider.cloudflare v2.4.1
+ provider.hcloud v1.16.0
```

**Comment by LKaemmerling** [comment]
There is a small timing issue on our CPX type vhosts when you create a server and then attach it to a network directly after the start actions were finished (Exactly this is done in the terraform provider). Were working on a fix for this on the vhosts.

**Comment by LKaemmerling** [comment]
@danielgrant @sebastiankr could you try it again? We updated the underlying host systems so the bug should be fixed.

**Comment by danielgrant** [comment]
Hi @LKaemmerling, I've just tested this and can confirm the issue appears to be resolved now 👍.

**Comment by SvenKube** [comment]
Hi @LKaemmerling , unfortunately I am still experiencing this issue with the _cpx_ instances. I've tried it multiple times with different instance sizes and locations but it made no difference.

Timestamp: Mi 20. Mai 23:17:27 CEST 2020
The versions I'm using:
```
Terraform v0.12.25
+ provider.hcloud v1.16.0
```

**Comment by LKaemmerling** [comment]
@SvenKube could you please give me a minimal reproduceable tf configuration? Do you attach Volumes and networks?

**Comment by SvenKube** [comment]
@LKaemmerling I have no volumes attached, just one network.

That's the terraform configuration:
```
variable "hcloud_token" {
}

variable "worker_count" {
  default = 3
}

provider "hcloud" {
  token = var.hcloud_token
}
### SSH-KEYS ###

data "hcloud_ssh_key" "key1" {
  fingerprint = "5e:d5:07:ab:ea:6a:1b:29:95:72:01:28:39:b4:6c:18"
}

### NETWORKS ###

resource "hcloud_network" "internal_network" {
  name     = "internal_network"
  ip_range = "10.0.0.0/16"
}

resource "hcloud_network_subnet" "subnet" {
  network_id = "${hcloud_network.internal_network.id}"
  type = "server"
  network_zone = "eu-central"
  ip_range   = "10.0.0.0/24"
}

### SERVERS ###

resource "hcloud_server" "worker" {
  count = var.worker_count

  name        = "worker-${count.index}"
  server_type = "cpx11"
  image       = "ubuntu-20.04"
  location    = "fsn1"

  ssh_keys = [data.hcloud_ssh_key.key1.id]
}

resource "hcloud_server_network" "internal_network-worker" {
  network_id = hcloud_network.internal_network.id
  server_id  = element(hcloud_server.worker.*.id, count.index)
  count      = var.worker_count
}
```

**Comment by eplightning** [comment]
Can confirm this issue still happens on `hel1` location when using server_type `cpx11`.

As for a workaround, powering off/on affected instances works for me.

**Comment by LKaemmerling** [comment]
We know that this bug is still available, unfortunately, it is not that easy fixable. We are still working on it on our host systems.

**Comment by flokli** [comment]
Is there any update to this? This issue was really hard to find, and it took me quite some time to realize it's a bug in your private nentworking that's causing this.

Even if this is a bug in the host systems, if it's not easy fixable, could it at least be worked around in the provider?

I mean, if detaching and reattaching it 2 seconds later is what's needed to work this around, could the terraform provide do the necessary API calls on resource creation?

**Comment by flokli** [comment]
Simply waiting some time before creating the resource seems to be fine - I pushed a workaround in https://github.com/hetznercloud/terraform-provider-hcloud/pull/264.

Would be nice if I could get some feedback from everybody that runs into this issue, and whether this works things around sufficiently for them.

I managed to successfully bring up some cpx21 nodes using that, but this doesn't mean it's a reliable fix for all machine types.

**Comment by flokli** [comment]
This issue should probably be renamed - it tracks the bug in the platform, not documentation about how to register a private interface - that's already covered in the docs.

**Comment by LKaemmerling** [comment]
@flokli We are still working on an on-host solution. As I said, it is not that easy and only affects the `cpx` types when created through terraform (basically because terraform performs the different tasks really fast). We already have a solution for the terraform provider under the hood, if the fix we try won't bring the expected result we will publish a bug fix release with a similar solution like you proposed.

I personally want to really avoid having a fix for this within our several integrations, as this is "just" a "dirty" workaround. A fix in the underlying platform would be better and as I said we are working on it.

**Comment by flokli** [comment]
Understood. However, this providers' main use case is probably creating servers, and if creating `cpx` instances with private networks (at least if you create both in a single run), is broken, I'd expect a big fat warning in the docs, and given it wasn't fixed in the platform for months, probably a low-effort, easy to later-revert workaround in the provider is probably fine.

**Comment by LKaemmerling** [comment]
@flokli and all the others, we deployed mitigation of this problem on our vhosts. Could you please retest it? I wasn't able to reproduce it with terraform on my end. It might be needed to sleep a second or two after the server started (you could use cloud-init for this). I will close this issue for now, if you still encounter this problem we will reopen this issue. Thank you for your long staying power. We tried to find a good fix on our vhosts that wouldn't lock the vhost for a certain time.

**Comment by flokli** [comment]
I can confirm the problem doesn't occur anymore. Thanks for fixing this on the host side!

**Comment by AMKamel** [comment]
I am still facing the same problem
![image](https://user-images.githubusercontent.com/14953512/146498755-f9cd602f-b6aa-4121-ad22-eb64d2c9f644.png)
![image](https://user-images.githubusercontent.com/14953512/146498807-532fa0d2-0515-4e37-9227-c36010c4a596.png)

hcloud version 1.32.2

**Comment by LKaemmerling** [comment]
Hey @AMKamel,

we currently have a smaller issue there, autoconfiguration does currently not work. We work on a solution.

**Comment by LKaemmerling** [comment]
Hey @AMKamel,

can you please try it again?

**Comment by AMKamel** [comment]
@LKaemmerling working at my side now, but I have also introduced reboot to cloud-init script.

**Comment by LKaemmerling** [comment]
> @LKaemmerling working at my side now, but I have also introduced reboot to cloud-init script.

Hey @AMKamel,

thanks, but this would not have solved the issue :) We had a problem with our mac generation as you can see on the image. The udev rule that "configures" the network interface only matched on Macs starting with `86:00:00`, but as you see in your screenshot the mac starts with `86:00:01` :)

**Comment by AMKamel** [comment]
OK, great I will remove the reboot then to save time :+1:

**Comment by niscinfo** [comment]
Hi all, 

I had same issue with terraform 1.0+ when affecting static hetzner private cloud IPs. 
It failed also with 86:00:00:xx:xx:xx MAC addresses. 
At the end I found a workaround in terraform by just waiting a little bit before affecting the private ip with time_sleep instruction. 

_resource "hcloud_server" "test" {
  ... your specs ... 
}
**resource "time_sleep" "test" {
    create_duration = "30s" 
    depends_on = [ hcloud_server.test ]
}**
resource hcloud_server_network "test" {
  server_id = hcloud_server.test.id
  network_id = hcloud_network.mynet.id 
  ip = "myip" 
  **depends_on = [ time_sleep.test ]**
}_

I tried much times to destroy / create it works ... The 30 seconds delay is arbitrary maybe it could be less. 

Regards

**Comment by niscinfo** [comment]
I also just tried to affect an alias IP to the server with terraform .. only the normal private ip is affected not the alias. 

_resource hcloud_server_network "test" {
server_id = hcloud_server.test.id
network_id = hcloud_network.mynet.id
ip = "myip"
alias_ips = [ "secondip" ]
depends_on = [ time_sleep.test ]
}_
