### ISSUE TITLE
use_private_ip=true in hcloud_load_balancer target does not work

### ISSUE THREAD

**Issue by vmozghovyi** [hetznercloud/terraform-provider-hcloud#170]
I have described terraform resource like:
```
resource "hcloud_load_balancer" "workers" {
  count = length(local.workers.hcloud_balancers)
  name  = "balancer-${local.workers.hcloud_balancers[count.index].name}-${format("%02d", count.index + 1)}.${var.cluster_name}"
  load_balancer_type = local.workers.hcloud_balancers[count.index].type
  location = local.workers.hcloud_balancers[count.index].location
  labels = local.workers.hcloud_balancers[count.index].labels
  dynamic "target" {
    for_each = hcloud_server.workers[*].id
    content {
      type = "server"
      server_id = target.value
      use_private_ip = true
    }
  }
}
```
terraform aplly:
```resource "hcloud_load_balancer" "workers" {
      + id                 = (known after apply)
      + ipv4               = (known after apply)
      + ipv6               = (known after apply)
      + labels             = {
          + "node_group" = "workers"
        }
      + load_balancer_type = "lb11"
      + location           = "fsn1"
      + name               = "balancer-workers-01.k8s.mindklab.com"
      + network_id         = (known after apply)
      + network_ip         = (known after apply)
      + network_zone       = (known after apply)

      + algorithm {
          + type = (known after apply)
        }

      + target {
          + server_id      = (known after apply)
          + type           = "server"
          + use_private_ip = true
        }
      + target {
          + server_id      = (known after apply)
          + type           = "server"
          + use_private_ip = true
        }
      + target {
          + server_id      = (known after apply)
          + type           = "server"
          + use_private_ip = true
        }
    }
```

But targets were created without using private IP addresses. At the same time, I can manually recreate the target using private addresses via a web interface.

**Comment by LKaemmerling** [comment]
You need to attach the Load Balancer to a network with the `hcloud_load_balancer_network`  resource: https://www.terraform.io/docs/providers/hcloud/r/load_balancer_network.html

**Comment by vmozghovyi** [comment]
@LKaemmerling I have done it, but it doesn't help:
```
resource "hcloud_load_balancer" "masters" {
  count = length(local.masters.hcloud_balancers)
  name = "balancer-${local.masters.hcloud_balancers[count.index].name}-${format("%02d", count.index + 1)}.${var.cluster_name}"
  load_balancer_type = local.masters.hcloud_balancers[count.index].type
  location = local.masters.hcloud_balancers[count.index].location
  labels = local.masters.hcloud_balancers[count.index].labels
  dynamic "target" {
    for_each = hcloud_server.masters[*].id
    content {
      type = "server"
      server_id = target.value
      use_private_ip = true
    }
  }
}

resource "hcloud_load_balancer_network" "masters" {
  count = length(local.masters.hcloud_balancers)
  load_balancer_id = hcloud_load_balancer.masters[count.index].id
  network_id = hcloud_network.network.id
}

resource "hcloud_load_balancer_service" "masters" {
  count = length(local.masters_hcloud_balancers_services)
  load_balancer_id = local.masters_hcloud_balancers_services[count.index].load_balancer_id
  protocol = local.masters_hcloud_balancers_services[count.index].protocol
  listen_port = local.masters_hcloud_balancers_services[count.index].listen_port
  destination_port = local.masters_hcloud_balancers_services[count.index].destination_port
  proxyprotocol = local.masters_hcloud_balancers_services[count.index].proxyprotocol
  dynamic "health_check" {
    for_each = local.masters_hcloud_balancers_services[count.index].health_checks
    content {
      protocol = health_check.value.protocol
      port = health_check.value.port
      interval = health_check.value.interval
      timeout = health_check.value.timeout
    }
  }
}
```
![image](https://user-images.githubusercontent.com/22145290/85729774-c1a6b600-b701-11ea-8db5-8799f0ae1c3a.png)
![image](https://user-images.githubusercontent.com/22145290/85729828-cd927800-b701-11ea-8a40-fb9ec5adb5df.png)

**Comment by fhofherr** [comment]
Hi @vmozgovoy and sorry for the late reply. We found an issue with the `use_private_ip` flag wich is fixed in version 1.18.0 of the Terraform provider. The new version should get released during the course of the day.

**Comment by z3dm4n** [comment]
Unfortunately this still doesn't do the trick via terraform, but manually inside the WebUI it works out.

Targets are not added by terraform, but I can add the target after the failed terraform run inside Hetzner Cloud WebUI.

```
Error: add server target: server is not attached to the load balancer's network (service_error)

  on main.tf line 132, in resource "hcloud_load_balancer_target" "lb-backend-target-db01":
 132: resource "hcloud_load_balancer_target" "lb-backend-target-db01" {

Error: add server target: server is not attached to the load balancer's network (service_error)

  on main.tf line 139, in resource "hcloud_load_balancer_target" "lb-backend-target-db02":
 139: resource "hcloud_load_balancer_target" "lb-backend-target-db02" {

Error: add server target: server is not attached to the load balancer's network (service_error)

  on main.tf line 146, in resource "hcloud_load_balancer_target" "lb-backend-target-db03":
 146: resource "hcloud_load_balancer_target" "lb-backend-target-db03" {
```

Code:

```hcl
resource "hcloud_load_balancer" "lb-backend" {
  name = "lb-backend"
  load_balancer_type = "lb11"
  network_zone = "eu-central"
  # location = "fsn1"
  labels = { type = "loadbalancer" }
  algorithm {
    type = "round_robin"
  }
}

resource "hcloud_load_balancer_network" "lb-backend-network" {
  load_balancer_id = hcloud_load_balancer.lb-backend.id
  network_id = hcloud_network.lan.id
  enable_public_interface = false
  ip = "10.0.1.2"
}

resource "hcloud_load_balancer_target" "lb-backend-target-db01" {
  type = "server"
  load_balancer_id = hcloud_load_balancer.lb-backend.id
  server_id = hcloud_server.db01.id
  use_private_ip = true
}

resource "hcloud_load_balancer_target" "lb-backend-target-db02" {
  type = "server"
  load_balancer_id = hcloud_load_balancer.lb-backend.id
  server_id = hcloud_server.db02.id
  use_private_ip = true
}

resource "hcloud_load_balancer_target" "lb-backend-target-db03" {
  type = "server"
  load_balancer_id = hcloud_load_balancer.lb-backend.id
  server_id = hcloud_server.db03.id
  use_private_ip = true
}
```

**Comment by fhofherr** [comment]
Hi @z3dm4n,

the error message `server is not attached to the load balancer's network` indicates the issue. Your servers are not attached to the load balancer network.

Please have a look at the `hcloud_server_network` resource. Basically your configuration should contain something like the following for each server:

```hcl
resource "hcloud_server_network" "db01_network" {
    server_id  = hcloud_server.db01.id
    network_id = hcloud_network.lan.id
}

resource "hcloud_server_network" "db02_network" {
    server_id  = hcloud_server.db02.id
    network_id = hcloud_network.lan.id
}

resource "hcloud_server_network" "db03_network" {
    server_id  = hcloud_server.db03.id
    network_id = hcloud_network.lan.id
}
```

**Comment by z3dm4n** [comment]
Actually, I have resources for this:

```hcl
resource "hcloud_server_network" "db01-network" {
  server_id = hcloud_server.db01.id
  network_id = hcloud_network.lan.id
  ip = "10.0.1.3"
}
```
...

**Comment by LKaemmerling** [comment]
@z3dm4n Could you please share a minimal reproducible terraform configuration (with all the parts)?

**Comment by z3dm4n** [comment]
main.tf (WIP)

```hcl
## Basics

# Set the variables values in terraform.tfvars
# or use the -var='hcloud_token="xxx"' CLI option
variable "hcloud_token" {}
variable "private_key_path" {}
variable "public_key_path" {}

# Setup OS image
variable "os_image" {
  type = string
  default = "centos-8"
}

# Setup server type
variable "server_type" {
  type = string
  default = "cx21"
}

# Configure the Hetzner Cloud provider
# Fixes https://github.com/terraform-providers/terraform-provider-hcloud/issues/170
provider "hcloud" {
  token = var.hcloud_token
  version = "~> 1.18"
}

# Import SSH key
resource "hcloud_ssh_key" "ha-cluster" {
  name = "ha-cluster"
  public_key = file(var.public_key_path)
}

## Networking

# Setup network
resource "hcloud_network" "lan" {
  name = "lan"
  ip_range = "10.0.0.0/16"
}

# Setup subnets
resource "hcloud_network_subnet" "frontend" {
  network_id = hcloud_network.lan.id
  type = "cloud"
  network_zone = "eu-central"
  ip_range = "10.0.0.0/24"
}

resource "hcloud_network_subnet" "backend" {
  network_id = hcloud_network.lan.id
  type = "cloud"
  network_zone = "eu-central"
  ip_range = "10.0.1.0/24"
}

# Setup server networking
resource "hcloud_server_network" "www01-network" {
  server_id = hcloud_server.www01.id
  network_id = hcloud_network.lan.id
  ip = "10.0.0.3"
}

resource "hcloud_server_network" "www02-network" {
  server_id = hcloud_server.www02.id
  network_id = hcloud_network.lan.id
  ip = "10.0.0.4"
}

resource "hcloud_server_network" "www03-network" {
  server_id = hcloud_server.www03.id
  network_id = hcloud_network.lan.id
  ip = "10.0.0.5"
}

resource "hcloud_server_network" "db01-network" {
  server_id = hcloud_server.db01.id
  network_id = hcloud_network.lan.id
  ip = "10.0.1.3"
}

resource "hcloud_server_network" "db02-network" {
  server_id = hcloud_server.db02.id
  network_id = hcloud_network.lan.id
  ip = "10.0.1.4"
}

resource "hcloud_server_network" "db03-network" {
  server_id = hcloud_server.db03.id
  network_id = hcloud_network.lan.id
  ip = "10.0.1.5"
}

## Loadbalancing

resource "hcloud_load_balancer" "lb-frontend" {
  name = "lb-frontend"
  load_balancer_type = "lb11"
  # network_zone = "eu-central"
  location = "fsn1"
  labels = { type = "loadbalancer" }
  algorithm {
    type = "round_robin"
  }
}

resource "hcloud_load_balancer" "lb-backend" {
  name = "lb-backend"
  load_balancer_type = "lb11"
  # network_zone = "eu-central"
  location = "fsn1"
  labels = { type = "loadbalancer" }
  algorithm {
    type = "round_robin"
  }
}

resource "hcloud_load_balancer_network" "lb-frontend-network" {
  load_balancer_id = hcloud_load_balancer.lb-frontend.id
  network_id = hcloud_network.lan.id
  enable_public_interface = true
  ip = "10.0.0.2"
}

resource "hcloud_load_balancer_network" "lb-backend-network" {
  load_balancer_id = hcloud_load_balancer.lb-backend.id
  network_id = hcloud_network.lan.id
  enable_public_interface = false
  ip = "10.0.1.2"
}

resource "hcloud_load_balancer_target" "lb-backend-target-db01" {
  type = "server"
  load_balancer_id = hcloud_load_balancer.lb-backend.id
  server_id = hcloud_server.db01.id
  use_private_ip = true
}

resource "hcloud_load_balancer_target" "lb-backend-target-db02" {
  type = "server"
  load_balancer_id = hcloud_load_balancer.lb-backend.id
  server_id = hcloud_server.db02.id
  use_private_ip = true
}

resource "hcloud_load_balancer_target" "lb-backend-target-db03" {
  type = "server"
  load_balancer_id = hcloud_load_balancer.lb-backend.id
  server_id = hcloud_server.db03.id
  use_private_ip = true
}

resource "hcloud_load_balancer_target" "lb-frontend-target-www01" {
  type = "server"
  load_balancer_id = hcloud_load_balancer.lb-frontend.id
  server_id = hcloud_server.www01.id
  use_private_ip = true
}

resource "hcloud_load_balancer_target" "lb-frontend-target-www02" {
  type = "server"
  load_balancer_id = hcloud_load_balancer.lb-frontend.id
  server_id = hcloud_server.www02.id
  use_private_ip = true
}

resource "hcloud_load_balancer_target" "lb-frontend-target-www03" {
  type = "server"
  load_balancer_id = hcloud_load_balancer.lb-frontend.id
  server_id = hcloud_server.www03.id
  use_private_ip = true
}

resource "hcloud_load_balancer_service" "lb-frontend-service" {
  load_balancer_id = hcloud_load_balancer.lb-frontend.id
  protocol = "http"
  health_check {
    protocol = "http"
    port = 80
    interval = 15
    timeout = 10
  }
}

resource "hcloud_load_balancer_service" "lb-backend-service" {
  load_balancer_id = hcloud_load_balancer.lb-backend.id
  protocol = "tcp"
  listen_port = 3306
  destination_port = 3306
  health_check {
    protocol = "tcp"
    port = 3306
    interval = 15
    timeout = 10
  }
}

## Servers

# www01
resource "hcloud_server" "www01" {
  name = "www01"
  image = var.os_image
  server_type = var.server_type
  location = "fsn1"
  ssh_keys = [ hcloud_ssh_key.ha-cluster.id ]
  labels = { type = "frontend" }
}

# www02
resource "hcloud_server" "www02" {
  name = "www02"
  image = var.os_image
  server_type = var.server_type
  location = "nbg1"
  ssh_keys = [ hcloud_ssh_key.ha-cluster.id ]
  labels = { type = "frontend" }
}

# www03
resource "hcloud_server" "www03" {
  name = "www03"
  image = var.os_image
  server_type = var.server_type
  location = "hel1"
  ssh_keys = [ hcloud_ssh_key.ha-cluster.id ]
  labels = { type = "frontend" }
}

# db01
resource "hcloud_server" "db01" {
  name = "db01"
  image = var.os_image
  server_type = var.server_type
  location = "fsn1"
  ssh_keys = [ hcloud_ssh_key.ha-cluster.id ]
  labels = { type = "backend" }
}

# db02
resource "hcloud_server" "db02" {
  name = "db02"
  image = var.os_image
  server_type = var.server_type
  location = "nbg1"
  ssh_keys = [ hcloud_ssh_key.ha-cluster.id ]
  labels = { type = "backend" }
}

# db03
resource "hcloud_server" "db03" {
  name = "db03"
  image = var.os_image
  server_type = var.server_type
  location = "hel1"
  ssh_keys = [ hcloud_ssh_key.ha-cluster.id ]
  labels = { type = "backend" }
}
```

terraform.tfvars:

```
hcloud_token = "XXX"
private_key_path = "../files/ha-cluster_rsa"
public_key_path = "../files/ha-cluster_rsa.pub"
```

**Comment by fhofherr** [comment]
@z3dm4n this version below works. I commented out some stuff not directly related to the problem. The key is the `depends_on` in the `hcloud_load_balancer_target` resources. Since `hcloud_server_network` and `hcloud_load_balancer_target` are not directly related, Terraform attempts to create the target before it attached the server to the network.

```
## Basics

# (commented out for testing)
# Set the variables values in terraform.tfvars
# or use the -var='hcloud_token="xxx"' CLI option
# variable "hcloud_token" {}
# variable "private_key_path" {}
# variable "public_key_path" {}

# Setup OS image
variable "os_image" {
  type = string
  default = "centos-8"
}

# Setup server type
variable "server_type" {
  type = string
  default = "cx21"
}

# Configure the Hetzner Cloud provider
# Fixes https://github.com/terraform-providers/terraform-provider-hcloud/issues/170
provider "hcloud" {
  # token = var.hcloud_token (commented out for testing)
  version = "~> 1.18"
}

# (commented out for testing)
# Import SSH key
# resource "hcloud_ssh_key" "ha-cluster" {
#   name = "ha-cluster"
#   public_key = file(var.public_key_path)
# }

## Networking

# Setup network
resource "hcloud_network" "lan" {
  name = "lan"
  ip_range = "10.0.0.0/16"
}

# Setup subnets
resource "hcloud_network_subnet" "frontend" {
  network_id = hcloud_network.lan.id
  type = "cloud"
  network_zone = "eu-central"
  ip_range = "10.0.0.0/24"
}

resource "hcloud_network_subnet" "backend" {
  network_id = hcloud_network.lan.id
  type = "cloud"
  network_zone = "eu-central"
  ip_range = "10.0.1.0/24"
}

# Setup server networking
resource "hcloud_server_network" "www01-network" {
  server_id = hcloud_server.www01.id
  network_id = hcloud_network.lan.id
  ip = "10.0.0.3"
}

resource "hcloud_server_network" "www02-network" {
  server_id = hcloud_server.www02.id
  network_id = hcloud_network.lan.id
  ip = "10.0.0.4"
}

resource "hcloud_server_network" "www03-network" {
  server_id = hcloud_server.www03.id
  network_id = hcloud_network.lan.id
  ip = "10.0.0.5"
}

resource "hcloud_server_network" "db01-network" {
  server_id = hcloud_server.db01.id
  network_id = hcloud_network.lan.id
  ip = "10.0.1.3"
}

resource "hcloud_server_network" "db02-network" {
  server_id = hcloud_server.db02.id
  network_id = hcloud_network.lan.id
  ip = "10.0.1.4"
}

resource "hcloud_server_network" "db03-network" {
  server_id = hcloud_server.db03.id
  network_id = hcloud_network.lan.id
  ip = "10.0.1.5"
}

## Loadbalancing

resource "hcloud_load_balancer" "lb-frontend" {
  name = "lb-frontend"
  load_balancer_type = "lb11"
  # network_zone = "eu-central"
  location = "fsn1"
  labels = { type = "loadbalancer" }
  algorithm {
    type = "round_robin"
  }
}

resource "hcloud_load_balancer" "lb-backend" {
  name = "lb-backend"
  load_balancer_type = "lb11"
  # network_zone = "eu-central"
  location = "fsn1"
  labels = { type = "loadbalancer" }
  algorithm {
    type = "round_robin"
  }
}

resource "hcloud_load_balancer_network" "lb-frontend-network" {
  load_balancer_id = hcloud_load_balancer.lb-frontend.id
  network_id = hcloud_network.lan.id
  enable_public_interface = true
  ip = "10.0.0.2"
}

resource "hcloud_load_balancer_network" "lb-backend-network" {
  load_balancer_id = hcloud_load_balancer.lb-backend.id
  network_id = hcloud_network.lan.id
  enable_public_interface = false
  ip = "10.0.1.2"
}

resource "hcloud_load_balancer_target" "lb-backend-target-db01" {
  type = "server"
  load_balancer_id = hcloud_load_balancer.lb-backend.id
  server_id = hcloud_server.db01.id
  use_private_ip = true

  depends_on = [
      hcloud_server_network.db01-network
  ]
}

resource "hcloud_load_balancer_target" "lb-backend-target-db02" {
  type = "server"
  load_balancer_id = hcloud_load_balancer.lb-backend.id
  server_id = hcloud_server.db02.id
  use_private_ip = true

  depends_on = [
      hcloud_server_network.db02-network
  ]
}

resource "hcloud_load_balancer_target" "lb-backend-target-db03" {
  type = "server"
  load_balancer_id = hcloud_load_balancer.lb-backend.id
  server_id = hcloud_server.db03.id
  use_private_ip = true

  depends_on = [
      hcloud_server_network.db03-network
  ]
}

resource "hcloud_load_balancer_target" "lb-frontend-target-www01" {
  type = "server"
  load_balancer_id = hcloud_load_balancer.lb-frontend.id
  server_id = hcloud_server.www01.id
  use_private_ip = true

  depends_on = [
      hcloud_server_network.www01-network
  ]
}

resource "hcloud_load_balancer_target" "lb-frontend-target-www02" {
  type = "server"
  load_balancer_id = hcloud_load_balancer.lb-frontend.id
  server_id = hcloud_server.www02.id
  use_private_ip = true

  depends_on = [
      hcloud_server_network.www02-network
  ]
}

resource "hcloud_load_balancer_target" "lb-frontend-target-www03" {
  type = "server"
  load_balancer_id = hcloud_load_balancer.lb-frontend.id
  server_id = hcloud_server.www03.id
  use_private_ip = true

  depends_on = [
      hcloud_server_network.www03-network
  ]
}

resource "hcloud_load_balancer_service" "lb-frontend-service" {
  load_balancer_id = hcloud_load_balancer.lb-frontend.id
  protocol = "http"
  health_check {
    protocol = "http"
    port = 80
    interval = 15
    timeout = 10
  }
}

resource "hcloud_load_balancer_service" "lb-backend-service" {
  load_balancer_id = hcloud_load_balancer.lb-backend.id
  protocol = "tcp"
  listen_port = 3306
  destination_port = 3306
  health_check {
    protocol = "tcp"
    port = 3306
    interval = 15
    timeout = 10
  }
}

## Servers

# www01
resource "hcloud_server" "www01" {
  name = "www01"
  image = var.os_image
  server_type = var.server_type
  location = "fsn1"
  # ssh_keys = [ hcloud_ssh_key.ha-cluster.id ]
  labels = { type = "frontend" }
}

# www02
resource "hcloud_server" "www02" {
  name = "www02"
  image = var.os_image
  server_type = var.server_type
  location = "nbg1"
  # ssh_keys = [ hcloud_ssh_key.ha-cluster.id ]
  labels = { type = "frontend" }
}

# www03
resource "hcloud_server" "www03" {
  name = "www03"
  image = var.os_image
  server_type = var.server_type
  location = "hel1"
  # ssh_keys = [ hcloud_ssh_key.ha-cluster.id ]
  labels = { type = "frontend" }
}

# db01
resource "hcloud_server" "db01" {
  name = "db01"
  image = var.os_image
  server_type = var.server_type
  location = "fsn1"
  # ssh_keys = [ hcloud_ssh_key.ha-cluster.id ]
  labels = { type = "backend" }
}

# db02
resource "hcloud_server" "db02" {
  name = "db02"
  image = var.os_image
  server_type = var.server_type
  location = "nbg1"
  # ssh_keys = [ hcloud_ssh_key.ha-cluster.id ]
  labels = { type = "backend" }
}

# db03
resource "hcloud_server" "db03" {
  name = "db03"
  image = var.os_image
  server_type = var.server_type
  location = "hel1"
  # ssh_keys = [ hcloud_ssh_key.ha-cluster.id ]
  labels = { type = "backend" }
}
```

**Comment by z3dm4n** [comment]
Works! Thanks :+1: 
I just opened a small PR #172 for some little documentation fixes.
